install:
	go install .

build:
	go build .

js:
	gogio -target js .

ios:
	gogio -target ios -o memory.app .

android:
	gogio -target android .

clean:
	-rm -rf memory memory.app memory.ipa memory.apk
